"""
Render pipeline results into an audit-friendly Markdown + JSON report
pair, plus a raw evidence JSON dump.
"""
from __future__ import annotations

import json
from dataclasses import asdict
from datetime import datetime
from pathlib import Path
from typing import List

from .scope import Scope
from .triage import severity_summary, risk_score
from .vuln_rules import Finding

SEVERITY_EMOJI = {
    "critical": "🟥", "high": "🟧", "medium": "🟨", "low": "🟦", "info": "⬜",
}


def _timestamp() -> str:
    return datetime.now().strftime("%Y%m%d-%H%M%S")


def write_report(
    scope: Scope,
    findings: List[Finding],
    raw_evidence: dict,
    out_dir: str | Path = "reports",
) -> Path:
    ts = _timestamp()
    report_dir = Path(out_dir) / scope.engagement_id / ts
    report_dir.mkdir(parents=True, exist_ok=True)

    summary = severity_summary(findings)
    score = risk_score(findings)

    # Raw evidence — full audit trail
    (report_dir / "evidence.json").write_text(json.dumps(raw_evidence, indent=2, default=str))

    # Structured findings
    (report_dir / "findings.json").write_text(
        json.dumps([asdict(f) for f in findings], indent=2, default=str)
    )

    # Human-readable Markdown report
    lines = []
    lines.append(f"# Internal Security Assessment — {scope.engagement_id}")
    lines.append("")
    lines.append(f"- **Authorized by:** {scope.authorized_by}")
    lines.append(f"- **Authorization window:** {scope.start_date} → {scope.end_date}")
    lines.append(f"- **Generated:** {datetime.now().isoformat(timespec='seconds')}")
    lines.append(f"- **Safe mode:** {'ON (passive/non-intrusive checks only)' if scope.safe_mode else 'OFF'}")
    lines.append(f"- **Targets in scope:** {len(scope.targets)}")
    lines.append(f"- **Aggregate risk score:** {score} (higher = more attention needed)")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append("| Severity | Count |")
    lines.append("|---|---|")
    for sev in ("critical", "high", "medium", "low", "info"):
        lines.append(f"| {SEVERITY_EMOJI[sev]} {sev.title()} | {summary.get(sev, 0)} |")
    lines.append("")
    lines.append("## Findings")
    lines.append("")
    if not findings:
        lines.append("_No findings were generated. Either the scan produced no signal, or "
                      "every check passed cleanly._")
    for f in findings:
        lines.append(f"### {SEVERITY_EMOJI.get(f.severity, '')} [{f.severity.upper()}] {f.title}")
        lines.append(f"- **Target:** `{f.target}`")
        lines.append(f"- **Description:** {f.description}")
        if f.evidence:
            lines.append(f"- **Evidence:** `{f.evidence}`")
        if f.recommendation:
            lines.append(f"- **Recommendation:** {f.recommendation}")
        lines.append("")

    lines.append("## Scope covered")
    lines.append("")
    for t in scope.targets:
        lines.append(f"- `{t.host}` — {t.description or 'no description'}")
    lines.append("")
    lines.append("---")
    lines.append("_This report was generated by an automated, non-intrusive assessment "
                  "pipeline restricted to explicitly authorized targets. It is not a "
                  "substitute for manual validation before remediation prioritization._")

    report_path = report_dir / "report.md"
    report_path.write_text("\n".join(lines))

    return report_path
